fail_fast: true

repos:
  - repo: https://github.com/ambv/black
    rev: 22.3.0
    hooks:
      - id: black
        name: black
        entry: black
        language: system
        types: [python]


  - repo: local
    hooks:
      - id: pytest
        name: Check pytest unit tests pass
        entry: pytest
        pass_filenames: false
        language: system
        types: [python]